### ISSUE TITLE
[Help] Issue when using npm start

### ISSUE THREAD

**Issue by alterlove** [MasterIO02/xmrig-rp#1]
I got everything ready but after using npm start on powershell of git bash, it gives me the error of 

`SyntaxError: Invalid hexadecimal escape sequence` I already edited config.js witht the directory of xmrig, but still shows this, any help please?

**Comment by MasterIO02** [comment]
Thanks for reporting this issue!
You need to change the backslashs in the path of xmrig and the config by double backslashs or simple slashs.
NodeJS cannot read Windows paths properly, I will add this in the readme.
